
@rootUrl = http://localhost:8000
#API List

### Check server status

GET {{rootUrl}}

### Auth API 


### post new user
POST {{rootUrl}}/api/v1/auth/register 
Content-Type: application/json

{
    "fName":"Ram",
    "lName":"Sita",
    "email":"a@a.com",
    "password":"1234",
    "phone":"123456"
}